testing ci pipeline

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -8,77 +8,80 @@ on:
   #   branches: [ "**" ]
 
 jobs:
-  job1:
-    name: Job 1
+#   job1:
+#     name: Job 1
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Sleep and Run
+#       run: |
+#         echo "Sleeping for 10"
+#         sleep 10
+
+#   job2:
+#     name: Job 2
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Dependant is Running
+#       run: |
+#         echo "Completed job 2, but triggering failure"
+#         exit 1
+
+#   job3:
+#     name: Job 3
+#     needs: [job1, job2]
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Will never run
+#       run: |
+#         echo "If you can read this, the experiment failed"k
+  check-linting:
+    name: Check Code Format 
     runs-on: ubuntu-latest
 
     steps:
-    - name: Sleep and Run
-      run: |
-        echo "Sleeping for 10"
-        sleep 10
+      - name: Check out code
+        uses: actions/checkout@v5
 
-  job2:
-    name: Job 2
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: pyproject.toml
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v6
+        with:
+          version: "0.82.0"
+
+      - name: Install the project
+        run: uv sync --locked --all-extras --dev
+
+      - name: Ruff linting check
+        run: uv run ruff check src
+
+  unit-test: 
+    name: Check Code Format 
+    needs: check-linting
     runs-on: ubuntu-latest
-
+    
     steps:
-    - name: Dependant is Running
-      run: |
-        echo "Completed job 2, but triggering failure"
-        exit 1
+      - name: Check out code
+        uses: actions/checkout@v5
 
-  job3:
-    name: Job 3
-    needs: [job1, job2]
-    runs-on: ubuntu-latest
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: pyproject.toml
 
-    steps:
-    - name: Will never run
-      run: |
-        echo "If you can read this, the experiment failed"k
-  # check-linting:
-  #   name: Check Code Format 
-  #   runs-on: ubuntu-latest
+      - name: Install uv
+        uses: astral-sh/setup-uv@v6
+        with:
+          version: "0.82.0"
 
-  #   steps:
-  #     - uses: actions/checkout@v5
+      - name: Install the project
+        run: uv sync --locked --all-extras --dev
 
-  #     - name: Install uv
-  #       uses: astral-sh/setup-uv@v6
-  #       with:
-  #         version: "0..82.0"
-
-  #     - name: Set up Python
-  #       run: uv python install
-
-  #     - name: Install the project
-  #       run: uv sync --all-extras --dev
-
-  #     - name: Ruff linting check
-  #       run: uv run ruff check src
-
-  #     - name: Test code
-  #       run: uv run pytest -vs
-
-  # unit-test:
-  #   name: Run unit test and coverage report
-  #   runs-on: ubuntu-latest
-
-  #   steps:
-  #     - uses: actions/checkout@v4
-
-  #     - name: Install uv
-  #       uses: astral-sh/setup-uv@v5
-
-  #     - name: Set up Python
-  #       run: uv python install
-
-  #     - name: Install the project
-  #       run: uv sync --all-extras --dev
-
-  #     - name: Ruff linting check
-  #       run: uv run ruff check src
-
-  #     - name: Test code
-  #       run: uv run pytest -vs
+      - name: Ruff linting check
+        run: uv run ruff check src
